name: EditorConfig Checker

on:
  push:
    branches:
      - main
      - develop 
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  editorconfig:
    name: Run EditorConfig Checker
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run EditorConfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@main
